Repository One-Nth/One-Nth_BE, pull requests merged in 2025-08, with the labels that each got.

#73 ♻️ [Refactor] 상품명 지역필터링 적용 및 상품의 위도경도값 변경
  src/main/java/com/onenth/OneNth/domain/product/controller/PurchaseItemController.java
  src/main/java/com/onenth/OneNth/domain/product/controller/SharingItemController.java
  src/main/java/com/onenth/OneNth/domain/product/service/PurchaseItemService.java
  src/main/java/com/onenth/OneNth/domain/product/service/SharingItemService.java
  src/main/java/com/onenth/OneNth/global/external/kakao/service/GeoCodingService.java
Labels: ♻️ refactor, 🐛 bug

#77 ♻️ [Refactor] 같이사요 위도경도 반전 문제 해결(ONLINE) & 필드명 변경
  src/main/java/com/onenth/OneNth/domain/product/dto/PurchaseItemRequestDTO.java
  src/main/java/com/onenth/OneNth/domain/product/dto/PurchaseItemResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/product/service/PurchaseItemService.java
Labels: ♻️ refactor

#81 :art:[Style] 스웨거 명세서 수정
  src/main/java/com/onenth/OneNth/domain/product/controller/PurchaseItemController.java
  src/main/java/com/onenth/OneNth/domain/product/controller/SellerProfileController.java
  src/main/java/com/onenth/OneNth/domain/product/controller/SharingItemController.java
Labels: 📝 docs

#88 ✨[Feat] 상품 스크랩 등록&삭제 기능 구현
  src/main/generated/com/onenth/OneNth/domain/product/entity/scrap/QPurchaseItemScrap.java
  src/main/generated/com/onenth/OneNth/domain/product/entity/scrap/QSharingItemScrap.java
  src/main/java/com/onenth/OneNth/domain/product/controller/PurchaseItemController.java
  src/main/java/com/onenth/OneNth/domain/product/controller/ReviewController.java
  src/main/java/com/onenth/OneNth/domain/product/controller/SharingItemController.java
  src/main/java/com/onenth/OneNth/domain/product/converter/PurchaseItemConverter.java
  src/main/java/com/onenth/OneNth/domain/product/converter/SharingItemConverter.java
  src/main/java/com/onenth/OneNth/domain/product/dto/PurchaseItemListDTO.java
  src/main/java/com/onenth/OneNth/domain/product/dto/PurchaseItemRequestDTO.java
  src/main/java/com/onenth/OneNth/domain/product/dto/SharingItemListDTO.java
  src/main/java/com/onenth/OneNth/domain/product/entity/scrap/PurchaseItemScrap.java
  src/main/java/com/onenth/OneNth/domain/product/entity/scrap/SharingItemScrap.java
  src/main/java/com/onenth/OneNth/domain/product/repository/itemRepository/purchase/PurchaseItemRepository.java
  src/main/java/com/onenth/OneNth/domain/product/repository/itemRepository/purchase/PurchaseItemRepositoryCustom.java
  src/main/java/com/onenth/OneNth/domain/product/repository/itemRepository/purchase/PurchaseItemRepositoryImpl.java
  src/main/java/com/onenth/OneNth/domain/product/repository/scrapRepository/PurchaseItemScrapRepository.java
  src/main/java/com/onenth/OneNth/domain/product/repository/scrapRepository/SharingItemScrapRepository.java
  src/main/java/com/onenth/OneNth/domain/product/service/PurchaseItemService.java
  src/main/java/com/onenth/OneNth/domain/product/service/SharingItemService.java
Labels: ✨feature, ♻️ refactor, 🐛 bug

#91 ✨[Feat] 우리동네 관련 API 개선 및 추가구현
  src/main/generated/com/onenth/OneNth/domain/member/entity/QMember.java
  src/main/generated/com/onenth/OneNth/domain/member/entity/QMemberRegion.java
  src/main/generated/com/onenth/OneNth/domain/product/entity/scrap/QPurchaseItemScrap.java
  src/main/generated/com/onenth/OneNth/domain/product/entity/scrap/QSharingItemScrap.java
  src/main/java/com/onenth/OneNth/domain/member/converter/MemberConverter.java
  src/main/java/com/onenth/OneNth/domain/member/entity/MemberRegion.java
  src/main/java/com/onenth/OneNth/domain/member/repository/memberRepository/MemberRegionRepository.java
  src/main/java/com/onenth/OneNth/domain/member/settings/alert/generalAlert/controller/GeneralAlertController.java
  src/main/java/com/onenth/OneNth/domain/member/settings/alert/keywordAlert/controller/KeywordAlertController.java
  src/main/java/com/onenth/OneNth/domain/member/settings/controller/UserSettingsController.java
  src/main/java/com/onenth/OneNth/domain/member/settings/converter/UserSettingsConverter.java
  src/main/java/com/onenth/OneNth/domain/member/settings/dto/UserSettingsRequestDTO.java
  src/main/java/com/onenth/OneNth/domain/member/settings/dto/UserSettingsResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/member/settings/memberRegion/controller/MemberRegionController.java
  src/main/java/com/onenth/OneNth/domain/member/settings/memberRegion/converter/MemberRegionConverter.java
  src/main/java/com/onenth/OneNth/domain/member/settings/memberRegion/dto/MemberRegionRequestDTO.java
  src/main/java/com/onenth/OneNth/domain/member/settings/memberRegion/dto/MemberRegionResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/member/settings/memberRegion/service/MemberRegionCommandService.java
  src/main/java/com/onenth/OneNth/domain/member/settings/memberRegion/service/MemberRegionCommandServiceImpl.java
  src/main/java/com/onenth/OneNth/domain/member/settings/memberRegion/service/MemberRegionQueryService.java
  src/main/java/com/onenth/OneNth/domain/member/settings/memberRegion/service/MemberRegionQueryServiceImpl.java
  src/main/java/com/onenth/OneNth/domain/member/settings/service/UserSettingsCommandService.java
  src/main/java/com/onenth/OneNth/domain/member/settings/service/UserSettingsCommandServiceImpl.java
  src/main/java/com/onenth/OneNth/domain/member/settings/service/UserSettingsQueryService.java
  src/main/java/com/onenth/OneNth/domain/member/settings/service/UserSettingsQueryServiceImpl.java
  src/main/java/com/onenth/OneNth/domain/region/repository/RegionRepository.java
  src/main/java/com/onenth/OneNth/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#97 ✨[Feat] 지도 마커 표시, 지도 마커 상세 조회 api 구현
  src/main/java/com/onenth/OneNth/domain/map/controller/MapController.java
  src/main/java/com/onenth/OneNth/domain/map/converter/MapConverter.java
  src/main/java/com/onenth/OneNth/domain/map/dto/MapRequestDTO.java
  src/main/java/com/onenth/OneNth/domain/map/dto/MapResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/map/enums/MarkerType.java
  src/main/java/com/onenth/OneNth/domain/map/service/PostMapService.java
  src/main/java/com/onenth/OneNth/domain/map/service/PurchaseItemMapService.java
  src/main/java/com/onenth/OneNth/domain/map/service/RegionResolver.java
  src/main/java/com/onenth/OneNth/domain/map/service/SharingItemMapService.java
  src/main/java/com/onenth/OneNth/domain/member/repository/memberRepository/MemberRegionRepository.java
  src/main/java/com/onenth/OneNth/domain/post/repository/PostRepository.java
  src/main/java/com/onenth/OneNth/domain/post/repository/scrapRepository/ScrapRepository.java
  src/main/java/com/onenth/OneNth/domain/product/repository/itemRepository/purchase/PurchaseItemRepository.java
  src/main/java/com/onenth/OneNth/domain/product/repository/itemRepository/sharing/SharingItemRepository.java
  src/main/java/com/onenth/OneNth/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature

#99 ♻️[Refactor] 거래완료여부 상태 변경
  src/main/java/com/onenth/OneNth/domain/product/dto/PurchaseItemListDTO.java
  src/main/java/com/onenth/OneNth/domain/product/dto/PurchaseItemResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/product/dto/SharingItemListDTO.java
  src/main/java/com/onenth/OneNth/domain/product/dto/SharingItemResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/product/service/PurchaseItemService.java
  src/main/java/com/onenth/OneNth/domain/product/service/SharingItemService.java
Labels: ♻️ refactor, 🐛 bug

#103 ✨[Feat] 카카오 로그인 로직 수정
  src/main/java/com/onenth/OneNth/domain/auth/controller/KakaoAuthController.java
  src/main/java/com/onenth/OneNth/domain/auth/dto/KakaoRequestDTO.java
  src/main/java/com/onenth/OneNth/domain/auth/service/KakaoAuthService.java
  src/main/java/com/onenth/OneNth/domain/post/repository/scrapRepository/ScrapRepository.java
Labels: ✨feature

#106 ✨[Feat] 좌표 기반 지역 식별 API 구현 및 지도 관련 API 성능 개선
  src/main/java/com/onenth/OneNth/domain/map/controller/MapController.java
  src/main/java/com/onenth/OneNth/domain/map/converter/MapConverter.java
  src/main/java/com/onenth/OneNth/domain/map/dto/MapResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/map/service/MapRegionService.java
  src/main/java/com/onenth/OneNth/domain/map/service/PostMapService.java
  src/main/java/com/onenth/OneNth/domain/map/service/RegionResolver.java
  src/main/java/com/onenth/OneNth/domain/member/settings/memberRegion/dto/MemberRegionResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/member/settings/memberRegion/service/MemberRegionCommandServiceImpl.java
  src/main/java/com/onenth/OneNth/domain/post/repository/PostRepository.java
  src/main/java/com/onenth/OneNth/global/external/kakao/dto/GetRegionNameByCoordinatesResponseDTO.java
  src/main/java/com/onenth/OneNth/global/external/kakao/service/GeoCodingService.java
Labels: ✨feature

#111 ♻️ [Recycle] 패치조인 최적화, 페이징왜곡 위험성 제거 및 불필요한 코드 삭제
  src/main/java/com/onenth/OneNth/domain/product/converter/SharingItemConverter.java
  src/main/java/com/onenth/OneNth/domain/product/repository/itemRepository/purchase/PurchaseItemRepositoryImpl.java
  src/main/java/com/onenth/OneNth/domain/product/repository/itemRepository/sharing/SharingItemRepositoryCustom.java
  src/main/java/com/onenth/OneNth/domain/product/repository/itemRepository/sharing/SharingItemRepositoryImpl.java
  src/main/java/com/onenth/OneNth/domain/product/service/PurchaseItemService.java
  src/main/java/com/onenth/OneNth/domain/product/service/SharingItemService.java
Labels: ♻️ refactor, 🐛 bug

#112 ✨[Feat] 거래 및 사용자 통계 API 추가 구현
  src/main/generated/com/onenth/OneNth/domain/deal/entity/QDealCompletion.java
  src/main/generated/com/onenth/OneNth/domain/deal/entity/QDealConfirmation.java
  src/main/java/com/onenth/OneNth/domain/chat/repository/ChatRoomRepository.java
  src/main/java/com/onenth/OneNth/domain/deal/controller/DealController.java
  src/main/java/com/onenth/OneNth/domain/deal/converter/DealConverter.java
  src/main/java/com/onenth/OneNth/domain/deal/dto/DealResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/deal/entity/DealCompletion.java
  src/main/java/com/onenth/OneNth/domain/deal/entity/DealConfirmation.java
  src/main/java/com/onenth/OneNth/domain/deal/repository/DealCompletionRepository.java
  src/main/java/com/onenth/OneNth/domain/deal/repository/DealConfirmationRepository.java
  src/main/java/com/onenth/OneNth/domain/deal/service/DealCommandService.java
  src/main/java/com/onenth/OneNth/domain/deal/service/DealQueryService.java
  src/main/java/com/onenth/OneNth/domain/member/controller/MemberRestController.java
  src/main/java/com/onenth/OneNth/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/member/service/memberService/MemberQueryService.java
  src/main/java/com/onenth/OneNth/domain/member/service/memberService/MemberQueryServiceImpl.java
  src/main/java/com/onenth/OneNth/domain/product/controller/SellerProfileController.java
  src/main/java/com/onenth/OneNth/domain/product/converter/ReviewConverter.java
  src/main/java/com/onenth/OneNth/domain/product/dto/ReviewResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/product/dto/SellerProfileResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/product/entity/Item.java
  src/main/java/com/onenth/OneNth/domain/product/entity/PurchaseItem.java
  src/main/java/com/onenth/OneNth/domain/product/entity/SharingItem.java
  src/main/java/com/onenth/OneNth/domain/product/repository/itemRepository/purchase/PurchaseItemRepository.java
  src/main/java/com/onenth/OneNth/domain/product/repository/itemRepository/sharing/SharingItemRepository.java
  src/main/java/com/onenth/OneNth/domain/product/service/SellerProfileService/SellerProfileService.java
  src/main/java/com/onenth/OneNth/domain/product/service/reviewService/ReviewQueryServiceImpl.java
Labels: ✨feature, ♻️ refactor

#115 ✨[Feat] 게시글 조회 시, 이미지 관련 응답 추가
  src/main/java/com/onenth/OneNth/domain/post/controller/PostRestController.java
  src/main/java/com/onenth/OneNth/domain/post/dto/PostDetailResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/post/dto/PostListResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/post/service/PostQueryServiceImpl.java
Labels: ✨feature, ♻️ refactor

#128 🐛 [FIX] 오프라인 상품 등록시 입력받는 주소(읍/면/동
  src/main/java/com/onenth/OneNth/domain/product/service/PurchaseItemService.java
  src/main/java/com/onenth/OneNth/domain/product/service/SharingItemService.java
Labels: bug, ♻️ refactor

#132 ✨[Feat] Firebase FCM 알림 시스템 FCM 세팅
  .github/workflows/deploy-dev.yml
  .gitignore
  build.gradle
  src/main/generated/com/onenth/OneNth/domain/alert/entity/QAlert.java
  src/main/java/com/onenth/OneNth/domain/alert/controller/AlertController.java
  src/main/java/com/onenth/OneNth/domain/alert/controller/FcmController.java
  src/main/java/com/onenth/OneNth/domain/alert/converter/AlertConverter.java
  src/main/java/com/onenth/OneNth/domain/alert/dto/AlertResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/alert/dto/FcmRequestDTO.java
  src/main/java/com/onenth/OneNth/domain/alert/entity/Alert.java
  src/main/java/com/onenth/OneNth/domain/alert/entity/AlertType.java
  src/main/java/com/onenth/OneNth/domain/alert/entity/FcmToken.java
  src/main/java/com/onenth/OneNth/domain/alert/fcm/FcmClient.java
  src/main/java/com/onenth/OneNth/domain/alert/repository/AlertRepository.java
  src/main/java/com/onenth/OneNth/domain/alert/repository/FcmTokenRepository.java
  src/main/java/com/onenth/OneNth/domain/alert/service/AlertCommandService.java
  src/main/java/com/onenth/OneNth/domain/alert/service/FcmService.java
  src/main/java/com/onenth/OneNth/domain/member/entity/MemberAlertSetting.java
  src/main/java/com/onenth/OneNth/domain/member/settings/alert/generalAlert/controller/GeneralAlertController.java
  src/main/java/com/onenth/OneNth/domain/member/settings/alert/generalAlert/converter/GeneralAlertConverter.java
  src/main/java/com/onenth/OneNth/domain/member/settings/alert/generalAlert/service/GeneralAlertCommandService.java
  src/main/java/com/onenth/OneNth/domain/member/settings/alert/generalAlert/service/GeneralAlertCommandServiceImpl.java
  src/main/java/com/onenth/OneNth/global/configuration/FirebaseConfig.java
  src/main/resources/application.yml
Labels: ✨feature, ♻️ refactor

#134 ♻️[Refactor] 거래후기 관련 API 응답 형식 변경
  src/main/java/com/onenth/OneNth/domain/product/converter/ReviewConverter.java
  src/main/java/com/onenth/OneNth/domain/product/dto/ReviewResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/product/service/reviewService/ReviewQueryServiceImpl.java
Labels: ♻️ refactor

#137 🐛 [Fix] 상품 전체 조회 시 PurchaseMethod, 사진 반환 추가 및 불필요한 디버깅 로그 제거
  src/main/java/com/onenth/OneNth/domain/product/converter/PurchaseItemConverter.java
  src/main/java/com/onenth/OneNth/domain/product/converter/SharingItemConverter.java
  src/main/java/com/onenth/OneNth/domain/product/dto/PurchaseItemListDTO.java
  src/main/java/com/onenth/OneNth/domain/product/dto/SharingItemListDTO.java
  src/main/java/com/onenth/OneNth/domain/product/repository/itemRepository/ItemImageRepository.java
  src/main/java/com/onenth/OneNth/domain/product/service/PurchaseItemService.java
  src/main/java/com/onenth/OneNth/domain/product/service/SharingItemService.java
Labels: 🐛 bug

#140 🐛 [Fix] 게시글 상세 조회 시 태그, 장소, 링크 값 추가 제공
  src/main/java/com/onenth/OneNth/domain/post/dto/PostDetailResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/post/repository/tagRepository/PostTagRepository.java
  src/main/java/com/onenth/OneNth/domain/post/service/PostQueryServiceImpl.java
Labels: bug, 🐛 bug

#143 ✨[Feat] 사용자 신고, 차단 API 구현, 사용자 정보 프리뷰 응답형식 변경
  src/main/generated/com/onenth/OneNth/domain/chat/entity/QChatRoom.java
  src/main/java/com/onenth/OneNth/domain/chat/controller/ChatController.java
  src/main/java/com/onenth/OneNth/domain/chat/entity/ChatRoom.java
  src/main/java/com/onenth/OneNth/domain/chat/service/ChatCommandService.java
  src/main/java/com/onenth/OneNth/domain/chat/service/ChatCommandServiceImpl.java
  src/main/java/com/onenth/OneNth/domain/member/controller/MemberRestController.java
  src/main/java/com/onenth/OneNth/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/member/entity/Report.java
  src/main/java/com/onenth/OneNth/domain/member/entity/enums/ReportType.java
  src/main/java/com/onenth/OneNth/domain/member/repository/ReportRepository.java
  src/main/java/com/onenth/OneNth/domain/member/service/memberService/MemberCommandService.java
  src/main/java/com/onenth/OneNth/domain/member/service/memberService/MemberCommandServiceImpl.java
  src/main/java/com/onenth/OneNth/domain/member/service/memberService/MemberQueryServiceImpl.java
  src/main/java/com/onenth/OneNth/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature, ♻️ refactor

#159 ✨[Feat] 채팅방 목록 조회 응답 차단 여부 추가
  src/main/generated/com/onenth/OneNth/domain/alert/entity/QAlert.java
  src/main/generated/com/onenth/OneNth/domain/alert/entity/QFcmToken.java
  src/main/generated/com/onenth/OneNth/domain/chat/entity/QChatMessage.java
  src/main/generated/com/onenth/OneNth/domain/chat/entity/QChatRoom.java
  src/main/generated/com/onenth/OneNth/domain/chat/entity/QChatRoomMember.java
  src/main/generated/com/onenth/OneNth/domain/deal/entity/QDealCompletion.java
  src/main/generated/com/onenth/OneNth/domain/deal/entity/QDealConfirmation.java
  src/main/generated/com/onenth/OneNth/domain/member/entity/QBlock.java
  src/main/generated/com/onenth/OneNth/domain/member/entity/QMemberAlertSetting.java
  src/main/generated/com/onenth/OneNth/domain/member/entity/QMemberRegion.java
  src/main/generated/com/onenth/OneNth/domain/member/entity/QProductKeywordAlert.java
  src/main/generated/com/onenth/OneNth/domain/member/entity/QRegionKeywordAlert.java
  src/main/generated/com/onenth/OneNth/domain/member/entity/QReport.java
  src/main/generated/com/onenth/OneNth/domain/post/entity/QLike.java
  src/main/generated/com/onenth/OneNth/domain/post/entity/QPost.java
  src/main/generated/com/onenth/OneNth/domain/post/entity/QPostComment.java
  src/main/generated/com/onenth/OneNth/domain/post/entity/QScrap.java
  src/main/generated/com/onenth/OneNth/domain/product/entity/QPurchaseItem.java
  src/main/generated/com/onenth/OneNth/domain/product/entity/QSharingItem.java
  src/main/generated/com/onenth/OneNth/domain/product/entity/review/QPurchaseReview.java
  src/main/generated/com/onenth/OneNth/domain/product/entity/review/QSharingReview.java
  src/main/generated/com/onenth/OneNth/domain/product/entity/scrap/QPurchaseItemScrap.java
  src/main/generated/com/onenth/OneNth/domain/product/entity/scrap/QSharingItemScrap.java
  src/main/java/com/onenth/OneNth/domain/chat/converter/ChatConverter.java
  src/main/java/com/onenth/OneNth/domain/chat/dto/ChatResponseDTO.java
  src/main/java/com/onenth/OneNth/domain/chat/service/ChatCommandServiceImpl.java
  src/main/java/com/onenth/OneNth/domain/chat/service/ChatQueryServiceImpl.java
  src/main/java/com/onenth/OneNth/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨feature, ♻️ refactor
